<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
     <Nullable>enable</Nullable>
    <NoWarn>NU1903</NoWarn>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets/appicon.ico</ApplicationIcon>
    <AssemblyName>WifiSender</AssemblyName>
    <Authors>WifiSender</Authors>
    <Product>WifiSender</Product>
    <Description>Cross-platform file transfer over WiFi or LAN</Description>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models/" />
    <Compile Remove="Engine\**" />
    <EmbeddedResource Remove="Engine\**" />
    <None Remove="Engine\**" />
    <AvaloniaResource Include="Assets/**" />
    <AvaloniaResource Include="DesignSystem/**" />
    <EmbeddedResource Include="Assets/appicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Engine\WifiSender.Transfer.csproj" />
  </ItemGroup>

  <Target Name="WriteVersionInfo" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)/dist" />
    <WriteLinesToFile
      File="$(MSBuildProjectDirectory)/dist/version.txt"
      Lines="$(Version)"
      Overwrite="true" />
  </Target>
</Project>
