<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WifiSender.Transfer</AssemblyName>
    <RootNamespace>WifiSender.Transfer</RootNamespace>
    <LangVersion>latest</LangVersion>
    <NoWarn>NU1903;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Bench\**" />
    <EmbeddedResource Remove="Bench\**" />
    <None Remove="Bench\**" />
  </ItemGroup>

</Project>
